---

- hosts: localhost
  connection: local   

  tasks:
    - name: ensure a container is running
      docker_container:
        name: my_container
        state: started
        image: "rranga99/techpreneursrsm:1.0.0"
        pull: true
        ports:
          - "8000:80"
