name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REPO_NAME: techpreneursrsm
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: echo repo values
      run: echo "The repo is ${{secrets.DOCKER_USER}}/$REPO_NAME."
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/$REPO_NAME:$(date +%s)
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/$REPO_NAME
